on:
  repository_dispatch:
    types: publish

jobs:
      
  publish_npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - name: Remove .github directory, useless on 'latest' branch
      run: rm -r .github
    - name: Remove branch 'latest' 
      continue-on-error: true
      run: |
        git branch -d latest || true
        git push origin :latest
    - name: Create the new 'latest' branch
      run: |
        git branch latest
        git checkout latest
    - uses: actions/setup-node@v3.8.1
    - uses: bahmutov/npm-install@v1
    - run: npm run enable_short_import_path
      env:
        DRY_RUN: "0"
    - name: (DEBUG) Show how the files have been moved to enable short import
      run: ls -lR
    - name: Publishing on NPM
      run: |
        if [ "$NPM_TOKEN" = "" ]; then
          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
          false
        fi
        echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
        npm publish
        rm .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Commit changes
      run: |
        git config --local user.email "ts_ci@github.com"
        git config --local user.name "ts_ci"
        git add -A
        git commit -am "Enable shorter import paths [automatic]"
    - run: git push origin latest
    - name: Create Release
      uses: garronej/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        tag_name: ${{ github.event.client_payload.to_version }}
        release_name: Release ${{ github.event.client_payload.to_version }}
        branch: latest
        draft: false
        prerelease: false
